# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    notification_template: Registration\notification.html.twig
    reset_template: Resetting\email.txt.twig

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    fos_user.doctrine_registry:
        alias: doctrine
        
    app.form.registration:
        class: Metropolia\DoggieBundle\Form\RegistrationFormType
        arguments: ["%fos_user.model.user.class%"]
        tags:
            - { name: "form.type", alias: "app_user_registration" }
        
        
    app_user.email_confirmation_listener:
        class: Metropolia\DoggieBundle\EventListener\EmailConfirmationListener
        arguments: ["@fos_user.mailer", "@fos_user.util.token_generator", "@router", "@session"]
        tags:
            - { name: kernel.event_subscriber }
            
    app_user.password_resetting_listener:
        class: Metropolia\DoggieBundle\EventListener\PasswordResettingListener
        arguments: ["@router"]
        tags:
            - { name: kernel.event_subscriber }

    app.my_awesome_mailer: 
        class: Metropolia\DoggieBundle\Mailer\MyAwesomeMailer
        arguments:
              - ["@mailer", "@router", "@templating"]
              - {confirmation: {template: %fos_user.registration.confirmation.template%}, from_email: {confirmation: %fos_user.registration.confirmation.from_email%, resetting: %fos_user.resetting.email.from_email%, notification: %fos_user.registration.confirmation.from_email%}, notification_template: %notification_template%, resetting_template: %reset_template%  }