MetropoliaDoggieBundle_home:
    path:     /
    defaults: { _controller: MetropoliaDoggieBundle:Page:index }
    methods: [GET, POST]
    
MetropoliaDoggieBundle_results:
    path:     /results
    defaults: { _controller: MetropoliaDoggieBundle:Page:results }
    methods: [GET]
    
MetropoliaDoggieBundle_events:
    path:     /events
    defaults: { _controller: MetropoliaDoggieBundle:Page:events }
    methods: [GET, POST]
    
MetropoliaDoggieBundle_single_event:
  path:  /events/{id}/
  defaults: { _controller: MetropoliaDoggieBundle:Page:showSingleEvent }
  methods: [POST]
  options:
        expose: true
        

    


